UPDATE DIRETORIA SET NAME = 'Regional RJ+ES+MG' WHERE NAME = 'Regional RJ+ES';

UPDATE UF SET DIRETORIA_ID = 3 WHERE NAME = 'MG';
UPDATE UF SET DIRETORIA_ID = 1 WHERE NAME = 'MA';
UPDATE UF SET DIRETORIA_ID = 1 WHERE NAME = 'PA';

DELETE FROM DIRETORIA WHERE ID = 6;
DELETE FROM DIRETORIA WHERE ID = 7;